export const VIDEO_LIMITS = {
  // 抖音 long-form commentary regularly runs past half an hour; the earlier 30-minute cap
  // rejected real videos users actually want to study.
  maxDurationSeconds: 3_600,
  maxSourceBytes: 400 * 1024 * 1024,
  maxAudioBytes: 24 * 1024 * 1024,
  maxFrames: 24,
  // Frames are opt-in. They dominate token cost, they require a multimodal model (the default
  // text provider is not one, so they would fail closed anyway), and a narrated video is
  // understood from its transcript alone. Ask for them only when the picture carries the method.
  defaultFrames: 0,
  sceneThreshold: 0.3,
  // Mean absolute difference over 0..255 grayscale. Below this two scene-change frames are
  // the same shot with a moving subtitle or a hand, and keeping both wastes model context.
  frameDistance: 6,
  maxTranscriptCharacters: 60_000,
  // SenseVoice and TeleSpeech return one unsegmented block, so slicing the audio is the only way
  // to give the model timestamps it can line up against the extracted frames.
  chunkSeconds: 60,
  maxChunks: 60,
  maxAnalyses: 40,
  maxStoredBytes: 600 * 1024 * 1024,
} as const

// "noven" is the default because 抖音 refuses anonymous extraction outright ("Fresh cookies
// (not necessarily logged in) are needed"), and the browser sources cannot be relied on: on
// Chromium 127+ for Windows, App-Bound Encryption makes --cookies-from-browser fail with a
// DPAPI error. The app is itself a Chromium, so it can acquire those cookies directly.
export type VideoCookieSource = "none" | "noven" | "edge" | "firefox" | "chrome"

export const VIDEO_COOKIE_SOURCES: readonly VideoCookieSource[] = ["none", "noven", "edge", "firefox", "chrome"]

export function isVideoCookieSource(value: unknown): value is VideoCookieSource {
  return typeof value === "string" && VIDEO_COOKIE_SOURCES.includes(value as VideoCookieSource)
}

// Netscape cookie jar, the only format yt-dlp's --cookies accepts. Tab separated, and the
// leading "# Netscape HTTP Cookie File" line is load-bearing.
export function formatCookieJar(cookies: readonly { domain: string; path: string; secure: boolean; expiresAt?: number; name: string; value: string }[]) {
  const lines = cookies.map((cookie) => [
    cookie.domain,
    cookie.domain.startsWith(".") ? "TRUE" : "FALSE",
    cookie.path || "/",
    cookie.secure ? "TRUE" : "FALSE",
    String(Math.floor(cookie.expiresAt ?? 0)),
    cookie.name,
    cookie.value,
  ].join("\t"))
  return `# Netscape HTTP Cookie File\n# Generated by 诺文; do not edit.\n${lines.join("\n")}\n`
}

export interface VideoTranscriptPresent {
  available: true
  source: "native-subtitles" | "asr"
  language?: string
  model?: string
  cueCount: number
  characters: number
  fileName: "transcript.txt"
  sha256: string
}

export interface VideoTranscriptAbsent {
  available: false
  reason: "no_audio_stream" | "no_speech_detected" | "not_requested" | "transcription_unavailable"
}

export interface VideoFrameRecord {
  fileName: string
  index: number
  atSeconds: number
  bytes: number
  sha256: string
}

export interface VideoAnalysisManifest {
  schemaVersion: 1
  analysisId: string
  platform: "douyin"
  sourceUrl: string
  requestedUrl: string
  analyzedAt: string
  title: string
  author: string
  durationSeconds: number
  transcript: VideoTranscriptPresent | VideoTranscriptAbsent
  frames: VideoFrameRecord[]
  bytes: number
}

const shareTokenPattern = /^\/[A-Za-z0-9_-]{4,32}\/?$/u
const videoIdPattern = /^\/video\/(\d{6,32})\/?$/u
const sharePathPattern = /^\/share\/video\/(\d{6,32})\/?$/u

// A 抖音 share is normally pasted as a whole sentence:
// "7.85 复制打开抖音，看看【…的作品】… https://v.douyin.com/iRNBho6/ 复制此链接…"
// Accepting only a bare URL would reject the exact thing users actually have in their clipboard.
export function extractDouyinUrl(input: string) {
  const found = input.match(/https?:\/\/[^\s<>"'）)】]+/gu)?.map((candidate) => candidate.replace(/[.,;:!?]+$/u, ""))
  const matched = found?.map((candidate) => tryDouyinUrl(candidate)).find((candidate) => candidate !== undefined)
  if (matched) return matched
  throw new Error("video_invalid: 没有在这段内容里找到可识别的抖音视频链接。")
}

export function requireDouyinUrl(input: string) {
  const url = tryDouyinUrl(input)
  if (url) return url
  throw new Error("video_invalid: 只支持抖音视频链接（v.douyin.com 分享短链或 www.douyin.com/video/<id>）。")
}

// The canonical form is what gets written into the manifest, what the model must reproduce in a
// Skill's Source line, and what addresses the analysis on disk — so it must be derived, never
// echoed back from user input. Short links stay as-is here because only yt-dlp can resolve them.
export function canonicalDouyinUrl(videoId: string) {
  if (!/^\d{6,32}$/u.test(videoId)) throw new Error("video_invalid: 抖音视频 id 无效。")
  return `https://www.douyin.com/video/${videoId}`
}

export function decodeVideoManifest(input: unknown): VideoAnalysisManifest {
  const value = asRecord(input, "manifest")
  if (value.schemaVersion !== 1) throw new Error("video_persistence: 视频分析清单版本不受支持。")
  if (value.platform !== "douyin") throw new Error("video_persistence: 视频分析清单平台不受支持。")
  const transcript = asRecord(value.transcript, "manifest.transcript")
  const frames = Array.isArray(value.frames) ? value.frames.map((frame, index) => decodeFrame(frame, index)) : []
  return {
    schemaVersion: 1,
    analysisId: requireAnalysisId(value.analysisId),
    platform: "douyin",
    sourceUrl: requireText(value.sourceUrl, "manifest.sourceUrl"),
    requestedUrl: requireText(value.requestedUrl, "manifest.requestedUrl"),
    analyzedAt: requireText(value.analyzedAt, "manifest.analyzedAt"),
    title: typeof value.title === "string" ? value.title : "",
    author: typeof value.author === "string" ? value.author : "",
    durationSeconds: Number(value.durationSeconds) || 0,
    transcript: transcript.available === true
      ? {
        available: true,
        source: transcript.source === "native-subtitles" ? "native-subtitles" : "asr",
        ...(typeof transcript.language === "string" ? { language: transcript.language } : {}),
        ...(typeof transcript.model === "string" ? { model: transcript.model } : {}),
        cueCount: Number(transcript.cueCount) || 0,
        characters: Number(transcript.characters) || 0,
        fileName: "transcript.txt",
        sha256: requireText(transcript.sha256, "manifest.transcript.sha256"),
      }
      : { available: false, reason: decodeAbsentReason(transcript.reason) },
    frames,
    bytes: Number(value.bytes) || 0,
  }
}

export function requireAnalysisId(input: unknown) {
  const value = typeof input === "string" ? input : ""
  if (/^video_[0-9a-f]{16}$/u.test(value)) return value
  throw new Error("video_invalid: 视频分析 id 无效。")
}

export function timestamp(seconds: number) {
  const total = Math.max(0, Math.floor(seconds))
  return `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`
}

function tryDouyinUrl(input: string) {
  const url = parseUrl(input)
  if (!url) return undefined
  if (url.protocol !== "https:" && url.protocol !== "http:") return undefined
  if (url.username || url.password) return undefined
  if (url.port && url.port !== "443" && url.port !== "80") return undefined
  const host = url.hostname.toLowerCase()
  // Query strings on 抖音 links are pure tracking; dropping them shrinks what reaches yt-dlp.
  if (host === "v.douyin.com" && shareTokenPattern.test(url.pathname)) return `https://v.douyin.com${url.pathname.replace(/\/$/u, "")}`
  const videoId = (host === "www.douyin.com" || host === "douyin.com" ? url.pathname.match(videoIdPattern)?.[1] : undefined)
    ?? (host === "www.iesdouyin.com" || host === "iesdouyin.com" ? url.pathname.match(sharePathPattern)?.[1] : undefined)
  return videoId ? canonicalDouyinUrl(videoId) : undefined
}

function parseUrl(input: string) {
  try {
    return new URL(input.trim())
  } catch {
    return undefined
  }
}

function decodeFrame(input: unknown, position: number): VideoFrameRecord {
  const value = asRecord(input, "manifest.frames[]")
  return {
    fileName: requireFrameFileName(value.fileName),
    index: Number(value.index) || position + 1,
    atSeconds: Number(value.atSeconds) || 0,
    bytes: Number(value.bytes) || 0,
    sha256: requireText(value.sha256, "manifest.frames[].sha256"),
  }
}

function requireFrameFileName(input: unknown) {
  const value = typeof input === "string" ? input : ""
  if (/^frame-\d{3}\.jpg$/u.test(value)) return value
  throw new Error("video_persistence: 视频帧文件名无效。")
}

function decodeAbsentReason(input: unknown): VideoTranscriptAbsent["reason"] {
  if (input === "no_audio_stream" || input === "no_speech_detected" || input === "not_requested" || input === "transcription_unavailable") return input
  return "not_requested"
}

function requireText(input: unknown, name: string) {
  if (typeof input === "string" && input.trim()) return input.trim()
  throw new Error(`video_persistence: ${name} 缺失或无效。`)
}

function asRecord(input: unknown, name: string): Record<string, unknown> {
  if (typeof input === "object" && input !== null && !Array.isArray(input)) return input as Record<string, unknown>
  throw new Error(`video_persistence: ${name} 不是对象。`)
}
