import type { IdeaLibrarySeed } from "./idea-library-seeds"

const collectedAt = "2026-08-10T00:00:00.000+08:00"

export const onlineInspirationSeeds: IdeaLibrarySeed[] = [
  {
    id: "idea-028",
    sentence: "如果你身体的每个部分都被逐步替换，最终留下的那个人仍然是原来的你吗？",
    category: "启发",
    tags: ["忒修斯之船", "身份", "替换"],
    sourceUrl: "https://en.wikipedia.org/wiki/Ship_of_Theseus",
    sourceTitle: "Ship of Theseus",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从忒修斯之船思想实验转向人的连续身份。",
  },
  {
    id: "idea-029",
    sentence: "如果一台机器能让你终身体验完美幸福，但一切经历都是模拟的，你愿意永远接入吗？",
    category: "启发",
    tags: ["体验机", "幸福", "真实"],
    sourceUrl: "https://en.wikipedia.org/wiki/Experience_machine",
    sourceTitle: "Experience machine",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "用体验机追问幸福与真实经历的价值。",
  },
  {
    id: "idea-030",
    sentence: "如果改变轨道可以救下五个人却会让另一个无辜者死亡，你会不会动手？",
    category: "启发",
    tags: ["电车难题", "选择", "责任"],
    sourceUrl: "https://en.wikipedia.org/wiki/Trolley_problem",
    sourceTitle: "Trolley problem",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "保留电车难题的行动与不行动冲突。",
  },
  {
    id: "idea-031",
    sentence: "如果你所见的一切只是维持在培养缸中的大脑收到的信号，你还能怎样证明世界真实存在？",
    category: "启发",
    tags: ["缸中之脑", "现实", "怀疑"],
    sourceUrl: "https://en.wikipedia.org/wiki/Brain_in_a_vat",
    sourceTitle: "Brain in a vat",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由缸中之脑引出可验证现实的边界。",
  },
  {
    id: "idea-032",
    sentence: "如果一个人完全不懂中文，却能照规则给出所有正确回答，他真的理解中文吗？",
    category: "启发",
    tags: ["中文房间", "理解", "人工智能"],
    sourceUrl: "https://en.wikipedia.org/wiki/Chinese_room",
    sourceTitle: "Chinese room",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以中文房间区分正确输出与真正理解。",
  },
  {
    id: "idea-033",
    sentence: "如果制定社会规则时不知道自己将出生为谁，你会如何分配财富、权利和风险？",
    category: "启发",
    tags: ["无知之幕", "制度", "公平"],
    sourceUrl: "https://en.wikipedia.org/wiki/Original_position",
    sourceTitle: "Original position",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从原初状态与无知之幕引出制度设计。",
  },
  {
    id: "idea-034",
    sentence: "如果两个敌对国家永远无法确认对方是否合作，它们怎样才能走出反复背叛的循环？",
    category: "启发",
    tags: ["囚徒困境", "国家", "合作"],
    sourceUrl: "https://en.wikipedia.org/wiki/Prisoner%27s_dilemma",
    sourceTitle: "Prisoner's dilemma",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "把囚徒困境放大到长期国际关系。",
  },
  {
    id: "idea-035",
    sentence: "如果大气、海洋和轨道都无人拥有，人类要靠什么阻止每个人把共同资源用到枯竭？",
    category: "启发",
    tags: ["公地悲剧", "共同资源", "治理"],
    sourceUrl: "https://en.wikipedia.org/wiki/Tragedy_of_the_commons",
    sourceTitle: "Tragedy of the commons",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "将公地悲剧扩展到全球公共资源。",
  },
  {
    id: "idea-036",
    sentence: "如果你能回到过去改变一件微不足道的小事，最可能被彻底改写的会是哪段历史？",
    category: "启发",
    tags: ["蝴蝶效应", "时间旅行", "历史"],
    sourceUrl: "https://en.wikipedia.org/wiki/Butterfly_effect",
    sourceTitle: "Butterfly effect",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以初始条件敏感性触发具体历史推演。",
  },
  {
    id: "idea-037",
    sentence: "如果时间旅行者阻止了自己的祖辈相遇，那么究竟是谁完成了这次阻止？",
    category: "启发",
    tags: ["祖父悖论", "时间旅行", "因果"],
    sourceUrl: "https://en.wikipedia.org/wiki/Temporal_paradox",
    sourceTitle: "Temporal paradox",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "用祖父悖论追问自相矛盾的因果链。",
  },
  {
    id: "idea-038",
    sentence: "如果一本发明手册来自未来，而未来又只是照着这本手册发明了机器，最初的知识是谁创造的？",
    category: "启发",
    tags: ["自举悖论", "知识", "因果闭环"],
    sourceUrl: "https://en.wikipedia.org/wiki/Bootstrap_paradox",
    sourceTitle: "Bootstrap paradox",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "把自举悖论落实为没有起点的知识。",
  },
  {
    id: "idea-039",
    sentence: "如果一名宇航员高速远行后比留在地球的双胞胎年轻几十岁，他们之间的家庭关系还会保持原样吗？",
    category: "启发",
    tags: ["双生子佯谬", "时间膨胀", "家庭"],
    sourceUrl: "https://en.wikipedia.org/wiki/Twin_paradox",
    sourceTitle: "Twin paradox",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从相对论年龄差进一步追问社会关系。",
  },
  {
    id: "idea-040",
    sentence: "如果你的记忆只是宇宙随机涨落瞬间形成的错觉，你凭什么相信自己拥有过去？",
    category: "启发",
    tags: ["玻尔兹曼大脑", "记忆", "宇宙"],
    sourceUrl: "https://en.wikipedia.org/wiki/Boltzmann_brain",
    sourceTitle: "Boltzmann brain",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由玻尔兹曼大脑追问记忆与连续存在。",
  },
  {
    id: "idea-041",
    sentence: "如果宇宙如此古老而辽阔，为什么我们至今没有发现任何外星文明的明确痕迹？",
    category: "启发",
    tags: ["费米悖论", "外星文明", "宇宙"],
    sourceUrl: "https://en.wikipedia.org/wiki/Fermi_paradox",
    sourceTitle: "Fermi paradox",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "直接保留费米悖论的核心张力。",
  },
  {
    id: "idea-042",
    sentence: "如果所有文明都会在进入星际时代前遭遇同一道门槛，人类已经越过它了，还是正在接近它？",
    category: "启发",
    tags: ["大过滤器", "文明", "生存"],
    sourceUrl: "https://en.wikipedia.org/wiki/Great_Filter",
    sourceTitle: "Great Filter",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以大过滤器定位人类文明的未知阶段。",
  },
  {
    id: "idea-043",
    sentence: "如果宇宙中的文明都因暴露位置而被消灭，人类还应该主动向星空发送信息吗？",
    category: "启发",
    tags: ["黑暗森林", "主动搜寻", "风险"],
    sourceUrl: "https://en.wikipedia.org/wiki/Dark_forest_hypothesis",
    sourceTitle: "Dark forest hypothesis",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从黑暗森林假说引出是否广播位置的决策。",
  },
  {
    id: "idea-044",
    sentence: "如果先进文明一直把地球当作自然保护区观察，我们第一次发现观察者时应该揭穿他们吗？",
    category: "启发",
    tags: ["动物园假说", "观察者", "接触"],
    sourceUrl: "https://en.wikipedia.org/wiki/Zoo_hypothesis",
    sourceTitle: "Zoo hypothesis",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "把动物园假说转化为首次发现后的选择。",
  },
  {
    id: "idea-045",
    sentence: "如果地球生命最初来自陨石，人类找到播种我们的星球后会把那里视为故乡吗？",
    category: "启发",
    tags: ["胚种论", "生命起源", "故乡"],
    sourceUrl: "https://en.wikipedia.org/wiki/Panspermia",
    sourceTitle: "Panspermia",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由胚种论引出文明身份与故乡认定。",
  },
  {
    id: "idea-046",
    sentence: "如果一颗流浪行星闯入太阳系，人类应该争取把它捕获为新家园，还是尽力把它推离？",
    category: "启发",
    tags: ["流浪行星", "太阳系", "新家园"],
    sourceUrl: "https://en.wikipedia.org/wiki/Rogue_planet",
    sourceTitle: "Rogue planet",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以流浪行星制造生存风险与扩张机会的冲突。",
  },
  {
    id: "idea-047",
    sentence: "如果一颗宜居行星永远一面朝向恒星，文明会如何围绕昼夜交界线建立城市和国界？",
    category: "启发",
    tags: ["潮汐锁定", "昼夜边界", "城市"],
    sourceUrl: "https://en.wikipedia.org/wiki/Tidal_locking",
    sourceTitle: "Tidal locking",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从潮汐锁定推演恒昼、恒夜之间的文明布局。",
  },
  {
    id: "idea-048",
    sentence: "如果人类建造包围太阳的戴森群，谁有权决定每个世界可以分到多少阳光？",
    category: "启发",
    tags: ["戴森球", "能源", "分配"],
    sourceUrl: "https://en.wikipedia.org/wiki/Dyson_sphere",
    sourceTitle: "Dyson sphere",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "把巨型能源工程转化为光照分配制度。",
  },
  {
    id: "idea-049",
    sentence: "如果世代飞船抵达目的地时，后发的高速飞船已经在那里建立文明，船上几代人的牺牲还算有意义吗？",
    category: "启发",
    tags: ["世代飞船", "星际移民", "后来者"],
    sourceUrl: "https://en.wikipedia.org/wiki/Generation_ship",
    sourceTitle: "Generation ship",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "用航行技术迭代冲击世代飞船的共同使命。",
  },
  {
    id: "idea-050",
    sentence: "如果太空城里的后代坚信圆柱内部就是完整宇宙，第一批看见外部星空的人会怎样解释真相？",
    category: "启发",
    tags: ["奥尼尔圆柱", "封闭世界", "真相"],
    sourceUrl: "https://en.wikipedia.org/wiki/O%27Neill_cylinder",
    sourceTitle: "O'Neill cylinder",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从奥尼尔圆柱的封闭空间引出宇宙认知冲突。",
  },
  {
    id: "idea-051",
    sentence: "如果轨道碎片让地球几百年无法安全发射飞船，被困在地面的人类会如何重新理解天空？",
    category: "启发",
    tags: ["凯斯勒现象", "轨道碎片", "封锁"],
    sourceUrl: "https://en.wikipedia.org/wiki/Kessler_syndrome",
    sourceTitle: "Kessler syndrome",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "将轨道碰撞链扩展为长期文明封锁。",
  },
  {
    id: "idea-052",
    sentence: "如果能自我复制的纳米机器开始把整个生态系统当成原料，人类应该保留任何一台作为工具吗？",
    category: "启发",
    tags: ["灰蛊", "纳米机器", "生态"],
    sourceUrl: "https://en.wikipedia.org/wiki/Gray_goo",
    sourceTitle: "Gray goo",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从灰蛊设想追问危险技术是否值得保留。",
  },
  {
    id: "idea-053",
    sentence: "如果人工智能的进步快到人类无法预测下一年，法律应该约束当下的机器还是尚未出现的机器？",
    category: "启发",
    tags: ["技术奇点", "人工智能", "法律"],
    sourceUrl: "https://en.wikipedia.org/wiki/Technological_singularity",
    sourceTitle: "Technological singularity",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "把技术奇点的不确定性转化为治理难题。",
  },
  {
    id: "idea-054",
    sentence: "如果完整上传你的大脑会产生一个确信自己就是你的数字副本，你愿意让肉身版本被关闭吗？",
    category: "启发",
    tags: ["意识上传", "副本", "身份"],
    sourceUrl: "https://en.wikipedia.org/wiki/Mind_uploading",
    sourceTitle: "Mind uploading",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "用意识上传区分复制与主观延续。",
  },
  {
    id: "idea-055",
    sentence: "如果你的数字人格能在死后继续学习和说话，家人应该把它当成你、遗产，还是一个新生命？",
    category: "启发",
    tags: ["数字永生", "人格", "遗产"],
    sourceUrl: "https://en.wikipedia.org/wiki/Digital_immortality",
    sourceTitle: "Digital immortality",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由数字永生追问死后人格的法律与关系身份。",
  },
  {
    id: "idea-056",
    sentence: "如果每个人都无条件获得足够生活的收入，工作会变成责任、兴趣，还是新的身份特权？",
    category: "启发",
    tags: ["基本收入", "工作", "身份"],
    sourceUrl: "https://en.wikipedia.org/wiki/Universal_basic_income",
    sourceTitle: "Universal basic income",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从全民基本收入延伸到劳动意义的变化。",
  },
  {
    id: "idea-057",
    sentence: "如果黑死病从未席卷欧洲，土地、工资、宗教和王权会沿着怎样不同的道路发展？",
    category: "启发",
    tags: ["黑死病", "欧洲", "历史分叉"],
    sourceUrl: "https://en.wikipedia.org/wiki/Black_Death",
    sourceTitle: "Black Death",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以重大人口冲击缺席作为历史分叉。",
  },
  {
    id: "idea-058",
    sentence: "如果亚历山大图书馆及其学术传统完整延续到今天，人类会更早进入科学时代，还是更早形成知识垄断？",
    category: "启发",
    tags: ["亚历山大图书馆", "知识", "历史分叉"],
    sourceUrl: "https://en.wikipedia.org/wiki/Library_of_Alexandria",
    sourceTitle: "Library of Alexandria",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "不预设图书馆毁灭的单一事件，只推演学术机构持续存在。",
  },
  {
    id: "idea-059",
    sentence: "如果廉价活字印刷比现实早普及一千年，帝国、宗教和普通人的识字能力会怎样变化？",
    category: "启发",
    tags: ["印刷术", "识字", "历史分叉"],
    sourceUrl: "https://en.wikipedia.org/wiki/Printing_press",
    sourceTitle: "Printing press",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以廉价复制知识的时间提前推演制度后果。",
  },
  {
    id: "idea-060",
    sentence: "如果跨大西洋接触后最致命的传染病主要从美洲传向旧大陆，全球权力会怎样重新排列？",
    category: "启发",
    tags: ["哥伦布大交换", "传染病", "权力"],
    sourceUrl: "https://en.wikipedia.org/wiki/Columbian_exchange",
    sourceTitle: "Columbian exchange",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "反转哥伦布大交换中的疾病冲击方向。",
  },
  {
    id: "idea-061",
    sentence: "如果青铜时代晚期的贸易网络没有崩溃，地中海会形成一个延续至今的共同文明吗？",
    category: "启发",
    tags: ["青铜时代崩溃", "贸易网络", "地中海"],
    sourceUrl: "https://en.wikipedia.org/wiki/Late_Bronze_Age_collapse",
    sourceTitle: "Late Bronze Age collapse",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以区域体系未崩溃推演跨国文明延续。",
  },
  {
    id: "idea-062",
    sentence: "如果罗马帝国从未分裂，欧洲的语言、宗教和国家边界会变成什么样子？",
    category: "启发",
    tags: ["罗马帝国", "未分裂", "欧洲"],
    sourceUrl: "https://en.wikipedia.org/wiki/Roman_Empire",
    sourceTitle: "Roman Empire",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以帝国持续统一作为开放历史分叉。",
  },
  {
    id: "idea-063",
    sentence: "如果拜占庭帝国存续到工业时代，它会成为连接欧亚的现代国家，还是被自己的历史拖垮？",
    category: "启发",
    tags: ["拜占庭帝国", "工业时代", "欧亚"],
    sourceUrl: "https://en.wikipedia.org/wiki/Byzantine_Empire",
    sourceTitle: "Byzantine Empire",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "把长期帝国延续到现代化压力之下。",
  },
  {
    id: "idea-064",
    sentence: "如果蒙古帝国在继承中保持统一，横跨欧亚的道路、语言和技术交流会怎样改变世界？",
    category: "启发",
    tags: ["蒙古帝国", "欧亚", "交流"],
    sourceUrl: "https://en.wikipedia.org/wiki/Mongol_Empire",
    sourceTitle: "Mongol Empire",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以统一持续推演大陆尺度的流动网络。",
  },
  {
    id: "idea-065",
    sentence: "如果明代远洋船队持续航行数百年，海上贸易、殖民和世界地图会由谁来定义？",
    category: "启发",
    tags: ["郑和下西洋", "远洋", "世界秩序"],
    sourceUrl: "https://en.wikipedia.org/wiki/Ming_treasure_voyages",
    sourceTitle: "Ming treasure voyages",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "延续明代宝船航行并追问海洋秩序的定义权。",
  },
  {
    id: "idea-066",
    sentence: "如果工业革命首先发生在宋代中国，机器、科举、城市和全球贸易会怎样彼此改造？",
    category: "启发",
    tags: ["工业革命", "宋代", "机器"],
    sourceUrl: "https://en.wikipedia.org/wiki/Industrial_Revolution",
    sourceTitle: "Industrial Revolution",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "把工业化起点迁移到另一制度与技术环境。",
  },
  {
    id: "idea-067",
    sentence: "如果曼哈顿计划最终失败，第二次世界大战的结局与战后的核秩序会怎样变化？",
    category: "启发",
    tags: ["曼哈顿计划", "核武器", "二战"],
    sourceUrl: "https://en.wikipedia.org/wiki/Manhattan_Project",
    sourceTitle: "Manhattan Project",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以核武研发失败追问战争与威慑秩序。",
  },
  {
    id: "idea-068",
    sentence: "如果古巴导弹危机真的引发核战争，幸存国家会如何书写那十三天的责任？",
    category: "启发",
    tags: ["古巴导弹危机", "核战争", "责任"],
    sourceUrl: "https://en.wikipedia.org/wiki/Cuban_Missile_Crisis",
    sourceTitle: "Cuban Missile Crisis",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从危机升级推演战后政治记忆。",
  },
  {
    id: "idea-069",
    sentence: "如果互联网从一开始就是无广告、不可私有化的公共基础设施，今天的社交与权力会是什么样？",
    category: "启发",
    tags: ["互联网", "公共基础设施", "广告"],
    sourceUrl: "https://en.wikipedia.org/wiki/Internet",
    sourceTitle: "Internet",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "改变互联网所有权和商业化前提。",
  },
  {
    id: "idea-070",
    sentence: "如果廉价基因编辑在全球共同伦理规则形成前进入每个家庭，人类会先消灭疾病还是先制造新的阶级？",
    category: "启发",
    tags: ["CRISPR", "基因编辑", "阶级"],
    sourceUrl: "https://en.wikipedia.org/wiki/CRISPR",
    sourceTitle: "CRISPR",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从基因编辑普及速度追问健康与不平等。",
  },
  {
    id: "idea-071",
    sentence: "如果人类提前一百年确认一颗小行星将撞击地球，这个漫长倒计时会让文明合作还是分裂？",
    category: "启发",
    tags: ["小行星防御", "倒计时", "文明"],
    sourceUrl: "https://en.wikipedia.org/wiki/Asteroid_impact_avoidance",
    sourceTitle: "Asteroid impact avoidance",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由行星防御把灾难预警拉长到跨世代尺度。",
  },
  {
    id: "idea-072",
    sentence: "如果一次超级火山喷发让阳光连续十年减弱，哪些制度和生活方式能让城市撑过没有收成的年代？",
    category: "启发",
    tags: ["超级火山", "火山冬季", "城市生存"],
    sourceUrl: "https://en.wikipedia.org/wiki/Supervolcano",
    sourceTitle: "Supervolcano",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从超级喷发推演长期粮食与城市制度。",
  },
  {
    id: "idea-073",
    sentence: "如果地磁倒转在人类一代人的时间里发生，导航、迁徙、卫星和神话会怎样一起改变？",
    category: "启发",
    tags: ["地磁倒转", "导航", "迁徙"],
    sourceUrl: "https://en.wikipedia.org/wiki/Geomagnetic_reversal",
    sourceTitle: "Geomagnetic reversal",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "把地磁变化压缩到可由一代人亲历的尺度。",
  },
  {
    id: "idea-074",
    sentence: "如果地球突然失去月球，潮汐、夜晚、历法和人类文化中最先崩塌的会是什么？",
    category: "启发",
    tags: ["月球", "潮汐", "文化"],
    sourceUrl: "https://en.wikipedia.org/wiki/Moon",
    sourceTitle: "Moon",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从月球对地球与文化的多重作用发起连锁推演。",
  },
  {
    id: "idea-075",
    sentence: "如果一台古代机械能精确预测未来的日食和战争，它应当属于发现者、国家，还是所有会被预言影响的人？",
    category: "启发",
    tags: ["安提基特拉机械", "预言", "所有权"],
    sourceUrl: "https://en.wikipedia.org/wiki/Antikythera_mechanism",
    sourceTitle: "Antikythera mechanism",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从古代天文机械扩写为能够影响政治的预测装置。",
  },
]
export const onlineFantasySeeds: IdeaLibrarySeed[] = [
  {
    id: "idea-076",
    sentence: "海底出土的古代齿轮装置不只计算天象，还会提前刻出下一场战争的日期，各国只能争夺尚未转到眼前的那一圈刻度。",
    category: "幻想",
    tags: ["安提基特拉机械", "天文", "战争预言"],
    sourceUrl: "https://en.wikipedia.org/wiki/Antikythera_mechanism",
    sourceTitle: "Antikythera mechanism",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以古代齿轮式天文计算装置为触发点重新创作。",
  },
  {
    id: "idea-077",
    sentence: "一本无人能读懂的植物手稿被雨水浸透后，书中不存在的花开始从纸页发芽，根须则把零散文字重新排列成当天的天气。",
    category: "幻想",
    tags: ["伏尼契手稿", "植物", "未知文字"],
    sourceUrl: "https://en.wikipedia.org/wiki/Voynich_manuscript",
    sourceTitle: "Voynich manuscript",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "依据手稿的未知文字与植物插图重新创作。",
  },
  {
    id: "idea-078",
    sentence: "散落帝国边境的青铜十二面体其实是一组城市钥匙，只有把不同孔径同时对准星空，早已消失的道路才会重新出现。",
    category: "幻想",
    tags: ["罗马十二面体", "城市钥匙", "古道"],
    sourceUrl: "https://en.wikipedia.org/wiki/Roman_dodecahedron",
    sourceTitle: "Roman dodecahedron",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从用途不明的罗马十二面体扩写为配套装置。",
  },
  {
    id: "idea-079",
    sentence: "沙漠巨画不是给天空中的神观看，而是一份跨越千年的停战条约；当最后一条线被公路切断，签约双方重新收到了开战信号。",
    category: "幻想",
    tags: ["纳斯卡线", "沙漠", "停战条约"],
    sourceUrl: "https://en.wikipedia.org/wiki/Nazca_Lines",
    sourceTitle: "Nazca Lines",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以只能从大尺度辨认的地画构造跨时代契约。",
  },
  {
    id: "idea-080",
    sentence: "地下军阵中的陶俑会按照帝国旧官印逐级苏醒，而现代政府必须在全部军团睁眼前证明自己继承了两千年前的合法命令。",
    category: "幻想",
    tags: ["兵马俑", "官印", "军团"],
    sourceUrl: "https://en.wikipedia.org/wiki/Terracotta_Army",
    sourceTitle: "Terracotta Army",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从陪葬军阵与官僚秩序扩写为现代继承危机。",
  },
  {
    id: "idea-081",
    sentence: "北极种子库每年都会收到没有登记来源的新种子，它们长成的植物适应陌生天空，仿佛有人正为地球准备另一颗星球的农业。",
    category: "幻想",
    tags: ["种子库", "外星农业", "北极"],
    sourceUrl: "https://en.wikipedia.org/wiki/Svalbard_Global_Seed_Vault",
    sourceTitle: "Svalbard Global Seed Vault",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由全球作物种子备份设施扩写为未知世界的生态准备。",
  },
  {
    id: "idea-082",
    sentence: "南极冰川流出的血红盐水来自一座封闭百万年的地下城市，那里的居民把铁当作呼吸的一部分，也从未见过太阳。",
    category: "幻想",
    tags: ["血瀑布", "冰下城市", "铁"],
    sourceUrl: "https://en.wikipedia.org/wiki/Blood_Falls",
    sourceTitle: "Blood Falls",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以冰下高盐含铁水体造成的红色流出物为视觉触发点。",
  },
  {
    id: "idea-083",
    sentence: "荒漠里的石头只在无人注视的薄冰上移动，它们留下的轨迹连成一封写给卫星的长信，而人类直到最后一个字完成才读懂。",
    category: "幻想",
    tags: ["航行石", "荒漠", "轨迹文字"],
    sourceUrl: "https://en.wikipedia.org/wiki/Sailing_stones",
    sourceTitle: "Sailing stones",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "依据薄冰和风推动石块留下长轨迹的现象重新创作。",
  },
  {
    id: "idea-084",
    sentence: "极地海冰向下生长出冻结一切的盐水冰柱，海底聚落把它们当作倒悬的森林，并在每次寒潮来临前收割会移动的冰。",
    category: "幻想",
    tags: ["死亡冰柱", "海冰", "海底聚落"],
    sourceUrl: "https://en.wikipedia.org/wiki/Brinicle",
    sourceTitle: "Brinicle",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从低温浓盐水形成的海底冰柱扩写生态与聚落。",
  },
  {
    id: "idea-085",
    sentence: "一批被送入太空的缓步动物在休眠中穿过数百年，落到另一颗行星后苏醒，并把人类飞船当成了自己物种的远古遗迹。",
    category: "幻想",
    tags: ["缓步动物", "休眠", "太空"],
    sourceUrl: "https://en.wikipedia.org/wiki/Tardigrade",
    sourceTitle: "Tardigrade",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由缓步动物耐受极端环境与隐生状态重新创作。",
  },
  {
    id: "idea-086",
    sentence: "城市把黏菌培养成交通规划师，它每晚都能找出更高效的道路，直到某天主动切断了通往权力中心的全部路线。",
    category: "幻想",
    tags: ["黏菌", "交通网络", "城市"],
    sourceUrl: "https://en.wikipedia.org/wiki/Slime_mold",
    sourceTitle: "Slime mold",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从黏菌网络行为扩写为具有政治后果的城市规划。",
  },
  {
    id: "idea-087",
    sentence: "一种能回到幼年阶段的水母被制成长生药后，服药者每隔几十年就必须重新长大一次，并在童年法庭争夺自己的旧财产。",
    category: "幻想",
    tags: ["灯塔水母", "返老还童", "财产"],
    sourceUrl: "https://en.wikipedia.org/wiki/Turritopsis_dohrnii",
    sourceTitle: "Turritopsis dohrnii",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从水母生命周期逆转能力扩写为周期性人生制度。",
  },
  {
    id: "idea-088",
    sentence: "森林地下的菌根网络开始拒绝为伐木者的农田输送养分，村庄这才发现土地契约还需要得到整片森林的同意。",
    category: "幻想",
    tags: ["菌根网络", "森林", "土地契约"],
    sourceUrl: "https://en.wikipedia.org/wiki/Mycorrhizal_network",
    sourceTitle: "Mycorrhizal network",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由植物与真菌构成的地下网络扩写为生态协商主体。",
  },
  {
    id: "idea-089",
    sentence: "每一具沉入深海的鲸尸都会孕育一个延续数十年的微型王国，年轻潜水员必须在王国耗尽最后一块骨头前完成外交任务。",
    category: "幻想",
    tags: ["鲸落", "深海", "微型王国"],
    sourceUrl: "https://en.wikipedia.org/wiki/Whale_fall",
    sourceTitle: "Whale fall",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从鲸尸支撑长期深海生态群落扩写为有限寿命文明。",
  },
  {
    id: "idea-090",
    sentence: "冰封海洋世界的居民围绕海底热泉建立城市，他们从未见过恒星，并把来自上方冰层的第一束光判定为末日征兆。",
    category: "幻想",
    tags: ["深海热泉", "冰封海洋", "无光文明"],
    sourceUrl: "https://en.wikipedia.org/wiki/Hydrothermal_vent",
    sourceTitle: "Hydrothermal vent",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "以无需阳光的深海热泉生态推演无星空文明。",
  },
  {
    id: "idea-091",
    sentence: "少数人重新获得感知地磁的能力后，能沿着早已被城市覆盖的古老迁徙路线行走，也因此发现地下仍有一支迁徙中的人群。",
    category: "幻想",
    tags: ["磁感应", "迁徙路线", "地下人群"],
    sourceUrl: "https://en.wikipedia.org/wiki/Magnetoreception",
    sourceTitle: "Magnetoreception",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从动物磁感应导航扩写为人类感官与隐藏路线。",
  },
  {
    id: "idea-092",
    sentence: "王国训练能够模仿多种海洋生物的章鱼担任间谍，却没人知道回国接受授勋的究竟是原来的章鱼，还是它最后模仿的对象。",
    category: "幻想",
    tags: ["拟态章鱼", "间谍", "身份"],
    sourceUrl: "https://en.wikipedia.org/wiki/Mimic_octopus",
    sourceTitle: "Mimic octopus",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由拟态章鱼模仿多种动物的行为扩写身份悬念。",
  },
  {
    id: "idea-093",
    sentence: "一种真菌能迫使昆虫爬到最适合传播孢子的位置，山民却把受感染虫群的路线当成神谕，用来决定迁村和战争。",
    category: "幻想",
    tags: ["虫草菌", "行为操控", "神谕"],
    sourceUrl: "https://en.wikipedia.org/wiki/Ophiocordyceps_unilateralis",
    sourceTitle: "Ophiocordyceps unilateralis",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从寄生真菌改变蚂蚁行为扩写为人类占卜制度。",
  },
  {
    id: "idea-094",
    sentence: "能够再生肢体的水生民族把每一道旧伤都视为可以删除的历史，只有拒绝愈合的人才被允许担任法官和档案官。",
    category: "幻想",
    tags: ["美西螈", "再生", "历史"],
    sourceUrl: "https://en.wikipedia.org/wiki/Axolotl",
    sourceTitle: "Axolotl",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从美西螈肢体再生能力推演伤痕与制度记忆。",
  },
  {
    id: "idea-095",
    sentence: "整座城市像蚁群一样被视为一个超级生物，市民只是可替换的细胞，而谋杀案第一次迫使法庭判断个人是否拥有独立生命。",
    category: "幻想",
    tags: ["超级生物", "城市", "个人权利"],
    sourceUrl: "https://en.wikipedia.org/wiki/Superorganism",
    sourceTitle: "Superorganism",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "把群体作为超级生物的概念推演为城市法律。",
  },
  {
    id: "idea-096",
    sentence: "沙漠帝国把难民脱水封存，让他们以隐生状态等待雨季，却在百年后发现唤醒一个人需要另一个活人交出同等水分。",
    category: "幻想",
    tags: ["隐生", "脱水", "难民"],
    sourceUrl: "https://en.wikipedia.org/wiki/Cryptobiosis",
    sourceTitle: "Cryptobiosis",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "由极端环境下代谢活动降至难以测量的状态重新创作。",
  },
  {
    id: "idea-097",
    sentence: "深海民族用生物发光书写法律，每一条法规都必须活在某种生物体内，而物种灭绝也会让对应的罪名从世界上消失。",
    category: "幻想",
    tags: ["生物发光", "法律", "物种"],
    sourceUrl: "https://en.wikipedia.org/wiki/Bioluminescence",
    sourceTitle: "Bioluminescence",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从生物体产生光的现象扩写为活体文字制度。",
  },
  {
    id: "idea-098",
    sentence: "海底矿工开采冻结的甲烷水合物时唤醒了以气体交换信息的生态，随后每一次能源交易都被它们理解为一句宣战。",
    category: "幻想",
    tags: ["甲烷水合物", "海底采矿", "气体生命"],
    sourceUrl: "https://en.wikipedia.org/wiki/Methane_clathrate",
    sourceTitle: "Methane clathrate",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从海底甲烷水合物资源扩写为陌生生态与开采冲突。",
  },
  {
    id: "idea-099",
    sentence: "一座小镇把每年出现的舞蹈狂热改造成节日，直到新任医生发现舞者的路线其实在避开地下逐渐扩大的空洞。",
    category: "幻想",
    tags: ["舞蹈瘟疫", "节日", "地下空洞"],
    sourceUrl: "https://en.wikipedia.org/wiki/Dancing_plague_of_1518",
    sourceTitle: "Dancing plague of 1518",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从历史舞蹈狂热进一步扩写为集体预警机制。",
  },
  {
    id: "idea-100",
    sentence: "被旧地图记录了数百年的幽灵岛突然在所有现代导航仪上同时出现，岛上每栋房屋都挂着一位尚未出生者的姓名。",
    category: "幻想",
    tags: ["幽灵岛", "导航", "未来居民"],
    sourceUrl: "https://en.wikipedia.org/wiki/Phantom_island",
    sourceTitle: "Phantom island",
    sourceType: "encyclopedia-entry",
    collectedAt: collectedAt,
    status: "starter-sample",
    notes: "从长期存在于地图的虚构岛屿扩写为未来人口档案。",
  },
]
