import { readFile, writeFile } from "node:fs/promises"
import { join, resolve } from "node:path"

const repositoryRoot = resolve(import.meta.dirname, "..", "..")
const sourceRoot = join(repositoryRoot, "prototypes", "skills", "creatx-build-interactive-map")
const output = join(repositoryRoot, "creatx", "packages", "creative-skills", "src", "draw-map.ts")
const paths = [
  "SKILL.md",
  "agents/openai.yaml",
  "assets/viewer/app.js",
  "assets/viewer/index.html",
  "assets/viewer/styles.css",
  "references/base-map-quality.md",
  "references/output-contract.md",
  "references/region-plan-contract.md",
  "scripts/build-interactive-map.mjs",
  "scripts/derive-region-mask.mjs",
]
const files = Object.fromEntries(await Promise.all(paths.map(async (path) => [path, (await readFile(join(sourceRoot, ...path.split("/")))).toString("base64")])))

await writeFile(output, `// Generated by creatx/scripts/package-draw-map.ts from the reviewed readable Skill source.\nimport { DRAW_MAP_SKILL_NAME } from "./skill-names.ts"\n\nexport { DRAW_MAP_SKILL_NAME } from "./skill-names.ts"\n\nconst files = ${JSON.stringify(files, null, 2)} as const\n\nexport const DRAW_MAP_SKILL_FILES = files\nexport const DRAW_MAP_SKILL_SOURCE = Buffer.from(files["SKILL.md"], "base64").toString("utf8")\n`, "utf8")
