import { readFile, writeFile } from "node:fs/promises"
import { join, resolve } from "node:path"

const repositoryRoot = resolve(import.meta.dirname, "..", "..")
const sourceRoot = join(repositoryRoot, "prototypes", "skills", "creatx-causality")
const output = join(repositoryRoot, "creatx", "packages", "creative-skills", "src", "causality.ts")
const paths = [
  "SKILL.md",
  "agents/openai.yaml",
  "assets/viewer/app.js",
  "assets/viewer/index.html",
  "assets/viewer/styles.css",
  "references/input-contract.md",
  "scripts/build-causality.mjs",
]
const files = Object.fromEntries(await Promise.all(paths.map(async (path) => [path, (await readFile(join(sourceRoot, ...path.split("/")))).toString("base64")])))

await writeFile(output, `// Generated by creatx/scripts/package-causality.ts from the reviewed readable Skill source.\nimport { CAUSALITY_SKILL_NAME } from "./skill-names.ts"\n\nexport { CAUSALITY_SKILL_NAME } from "./skill-names.ts"\n\nconst files = ${JSON.stringify(files, null, 2)} as const\n\nexport const CAUSALITY_SKILL_FILES = files\nexport const CAUSALITY_SKILL_SOURCE = Buffer.from(files["SKILL.md"], "base64").toString("utf8")\n`, "utf8")
